services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx42
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/tools:/etc/nginx/tools
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file: .env

volumes:
  wordpress_volume:

networks:
  inception:
    name: inception
