services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx42
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/tools:/etc/nginx/tools
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb42
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    secrets:
      - source: db_root_password
        target: /run/secrets/db_root_password
      - source: db_password
        target: /run/secrets/db_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_INITDB_SKIP_TZINFO=1

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  wordpress_volume:
  db_volume:

networks:
  inception:
    name: inception
    driver: bridge
